import type {
  AuditEvent,
  Cluster,
  Environment,
  Instance,
  Profile,
  Revision,
  SecurityIncident,
} from "./types.ts";

export const PRIMARY_ENVIRONMENT_ID = "env-customer-service-prod";
export const OPEN_INCIDENT_ID = "sec-20260729-001";
export const STABLE_REVISION_ID = "rev-42";
export const FAILED_REVISION_ID = "rev-43";

export const MOCK_ENVIRONMENTS: readonly Environment[] = [
  {
    id: PRIMARY_ENVIRONMENT_ID,
    name: "Customer Service Production",
    project: "customer-service",
    owner: "cx-platform",
    status: "Running",
    endpoint: "https://customer-service-prod.demo.agentpaas.local",
    desiredRevisionId: STABLE_REVISION_ID,
    readyInstances: 3,
    desiredInstances: 3,
    runtimePlanId: "runtime-balanced",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    containerPort: 8080,
    endpointVisibility: "internal",
    sessionHeader: "X-Agent-Session-ID",
    secureTaskProfileId: "secure-task-hardened",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
    domainProfileId: "domain-customer-service",
  },
  {
    id: "env-customer-service-staging",
    name: "Customer Service Staging",
    project: "customer-service",
    owner: "cx-platform",
    status: "Deploying",
    endpoint: "",
    desiredRevisionId: "rev-50",
    readyInstances: 0,
    desiredInstances: 2,
    runtimePlanId: "runtime-burst",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-claims-prod",
    name: "Claims Production",
    project: "claims",
    owner: "claims-platform",
    status: "Degraded",
    endpoint: "https://claims-prod.demo.agentpaas.local",
    desiredRevisionId: "rev-60",
    readyInstances: 2,
    desiredInstances: 3,
    runtimePlanId: "runtime-high-memory",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    secureTaskProfileId: "secure-task-hardened",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-payments-prod",
    name: "Payments Production",
    project: "payments",
    owner: "payments-platform",
    status: "Running",
    endpoint: "https://payments-prod.demo.agentpaas.local",
    desiredRevisionId: "rev-70",
    readyInstances: 3,
    desiredInstances: 3,
    runtimePlanId: "runtime-secure",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    secureTaskProfileId: "secure-task-hardened",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-knowledge-prod",
    name: "Knowledge Production",
    project: "knowledge",
    owner: "knowledge-platform",
    status: "Running",
    endpoint: "https://knowledge-prod.demo.agentpaas.local",
    desiredRevisionId: "rev-80",
    readyInstances: 2,
    desiredInstances: 2,
    runtimePlanId: "runtime-balanced",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-developer-sandbox",
    name: "Developer Sandbox",
    project: "developer-experience",
    owner: "platform-engineering",
    status: "Stopped",
    endpoint: "",
    desiredRevisionId: "rev-90",
    readyInstances: 0,
    desiredInstances: 1,
    runtimePlanId: "runtime-burst",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-support-prod",
    name: "Support Production",
    project: "support",
    owner: "support-platform",
    status: "Running",
    endpoint: "https://support-prod.demo.agentpaas.local",
    desiredRevisionId: "rev-100",
    readyInstances: 3,
    desiredInstances: 3,
    runtimePlanId: "runtime-balanced",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-risk-prod",
    name: "Risk Production",
    project: "risk",
    owner: "risk-platform",
    status: "Degraded",
    endpoint: "https://risk-prod.demo.agentpaas.local",
    desiredRevisionId: "rev-110",
    readyInstances: 1,
    desiredInstances: 2,
    runtimePlanId: "runtime-high-memory",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    secureTaskProfileId: "secure-task-hardened",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-analytics-batch",
    name: "Analytics Batch",
    project: "analytics",
    owner: "data-platform",
    status: "Stopped",
    endpoint: "",
    desiredRevisionId: "rev-120",
    readyInstances: 0,
    desiredInstances: 2,
    runtimePlanId: "runtime-high-memory",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
  {
    id: "env-agent-lab",
    name: "Agent Lab",
    project: "agent-research",
    owner: "applied-ai",
    status: "Running",
    endpoint: "https://agent-lab.demo.agentpaas.local",
    desiredRevisionId: "rev-130",
    readyInstances: 3,
    desiredInstances: 3,
    runtimePlanId: "runtime-burst",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    identityProfileId: "identity-workload",
    loggingProfileId: "logging-audit",
  },
];

export const MOCK_REVISIONS: readonly Revision[] = [
  {
    id: STABLE_REVISION_ID,
    environmentId: PRIMARY_ENVIRONMENT_ID,
    sequence: 42,
    image: "registry.demo.local/customer-service:2026.07.28",
    imageDigest:
      "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    runtimePlanId: "runtime-balanced",
    ingressProfileId: "ingress-private",
    egressProfileId: "egress-restricted",
    status: "Stable",
    createdAt: "2026-07-28T09:00:00.000Z",
    createdBy: "release-bot",
  },
  {
    id: FAILED_REVISION_ID,
    environmentId: PRIMARY_ENVIRONMENT_ID,
    sequence: 43,
    image: "registry.demo.local/customer-service:2026.07.29",
    imageDigest:
      "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    runtimePlanId: "runtime-high-memory",
    ingressProfileId: "ingress-private-v2",
    egressProfileId: "egress-allowlist-v2",
    failureReason: "就绪探针连续 3 次超时，流量未切换到新版本。",
    status: "Failed",
    createdAt: "2026-07-29T06:10:00.000Z",
    createdBy: "release-bot",
  },
  {
    id: "rev-50",
    environmentId: "env-customer-service-staging",
    sequence: 50,
    image: "registry.demo.local/customer-service:staging",
    status: "Deploying",
    createdAt: "2026-07-29T08:00:00.000Z",
    createdBy: "cx-platform",
  },
  {
    id: "rev-60",
    environmentId: "env-claims-prod",
    sequence: 60,
    image: "registry.demo.local/claims:2026.07.25",
    status: "Stable",
    createdAt: "2026-07-25T10:00:00.000Z",
    createdBy: "claims-platform",
  },
  {
    id: "rev-70",
    environmentId: "env-payments-prod",
    sequence: 70,
    image: "registry.demo.local/payments:2026.07.27",
    status: "Stable",
    createdAt: "2026-07-27T10:00:00.000Z",
    createdBy: "payments-platform",
  },
  {
    id: "rev-80",
    environmentId: "env-knowledge-prod",
    sequence: 80,
    image: "registry.demo.local/knowledge:2026.07.26",
    status: "Stable",
    createdAt: "2026-07-26T10:00:00.000Z",
    createdBy: "knowledge-platform",
  },
  {
    id: "rev-90",
    environmentId: "env-developer-sandbox",
    sequence: 90,
    image: "registry.demo.local/developer-sandbox:2026.07.20",
    status: "Stable",
    createdAt: "2026-07-20T10:00:00.000Z",
    createdBy: "platform-engineering",
  },
  {
    id: "rev-100",
    environmentId: "env-support-prod",
    sequence: 100,
    image: "registry.demo.local/support:2026.07.24",
    status: "Stable",
    createdAt: "2026-07-24T10:00:00.000Z",
    createdBy: "support-platform",
  },
  {
    id: "rev-110",
    environmentId: "env-risk-prod",
    sequence: 110,
    image: "registry.demo.local/risk:2026.07.23",
    status: "Stable",
    createdAt: "2026-07-23T10:00:00.000Z",
    createdBy: "risk-platform",
  },
  {
    id: "rev-120",
    environmentId: "env-analytics-batch",
    sequence: 120,
    image: "registry.demo.local/analytics:2026.07.22",
    status: "Stable",
    createdAt: "2026-07-22T10:00:00.000Z",
    createdBy: "data-platform",
  },
  {
    id: "rev-130",
    environmentId: "env-agent-lab",
    sequence: 130,
    image: "registry.demo.local/agent-lab:2026.07.29",
    status: "Stable",
    createdAt: "2026-07-29T07:30:00.000Z",
    createdBy: "applied-ai",
  },
];

export const MOCK_INSTANCES: readonly Instance[] = [
  {
    id: "ins-cs-01",
    environmentId: PRIMARY_ENVIRONMENT_ID,
    revisionId: STABLE_REVISION_ID,
    status: "Ready",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-28T09:02:00.000Z",
  },
  {
    id: "ins-cs-02",
    environmentId: PRIMARY_ENVIRONMENT_ID,
    revisionId: STABLE_REVISION_ID,
    status: "Ready",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-28T09:02:10.000Z",
  },
  {
    id: "ins-cs-03",
    environmentId: PRIMARY_ENVIRONMENT_ID,
    revisionId: STABLE_REVISION_ID,
    status: "Ready",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-28T09:02:20.000Z",
  },
  {
    id: "ins-css-01",
    environmentId: "env-customer-service-staging",
    revisionId: "rev-50",
    status: "Starting",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-29T08:01:00.000Z",
  },
  {
    id: "ins-css-02",
    environmentId: "env-customer-service-staging",
    revisionId: "rev-50",
    status: "Starting",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-29T08:01:10.000Z",
  },
  {
    id: "ins-claims-01",
    environmentId: "env-claims-prod",
    revisionId: "rev-60",
    status: "Ready",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-25T10:02:00.000Z",
  },
  {
    id: "ins-claims-02",
    environmentId: "env-claims-prod",
    revisionId: "rev-60",
    status: "Ready",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-25T10:02:10.000Z",
  },
  {
    id: "ins-claims-03",
    environmentId: "env-claims-prod",
    revisionId: "rev-60",
    status: "Failed",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-25T10:02:20.000Z",
  },
  {
    id: "ins-payments-01",
    environmentId: "env-payments-prod",
    revisionId: "rev-70",
    status: "Ready",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-27T10:02:00.000Z",
  },
  {
    id: "ins-payments-02",
    environmentId: "env-payments-prod",
    revisionId: "rev-70",
    status: "Ready",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-27T10:02:10.000Z",
  },
  {
    id: "ins-payments-03",
    environmentId: "env-payments-prod",
    revisionId: "rev-70",
    status: "Ready",
    clusterId: "cluster-tenant-central",
    startedAt: "2026-07-27T10:02:20.000Z",
  },
  {
    id: "ins-knowledge-01",
    environmentId: "env-knowledge-prod",
    revisionId: "rev-80",
    status: "Ready",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-26T10:02:00.000Z",
  },
  {
    id: "ins-knowledge-02",
    environmentId: "env-knowledge-prod",
    revisionId: "rev-80",
    status: "Ready",
    clusterId: "cluster-tenant-central",
    startedAt: "2026-07-26T10:02:10.000Z",
  },
  {
    id: "ins-sandbox-01",
    environmentId: "env-developer-sandbox",
    revisionId: "rev-90",
    status: "Stopped",
    clusterId: "cluster-tenant-central",
    startedAt: "2026-07-20T10:02:00.000Z",
  },
  {
    id: "ins-support-01",
    environmentId: "env-support-prod",
    revisionId: "rev-100",
    status: "Ready",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-24T10:02:00.000Z",
  },
  {
    id: "ins-support-02",
    environmentId: "env-support-prod",
    revisionId: "rev-100",
    status: "Ready",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-24T10:02:10.000Z",
  },
  {
    id: "ins-support-03",
    environmentId: "env-support-prod",
    revisionId: "rev-100",
    status: "Ready",
    clusterId: "cluster-tenant-central",
    startedAt: "2026-07-24T10:02:20.000Z",
  },
  {
    id: "ins-risk-01",
    environmentId: "env-risk-prod",
    revisionId: "rev-110",
    status: "Ready",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-23T10:02:00.000Z",
  },
  {
    id: "ins-risk-02",
    environmentId: "env-risk-prod",
    revisionId: "rev-110",
    status: "Failed",
    clusterId: "cluster-tenant-central",
    startedAt: "2026-07-23T10:02:10.000Z",
  },
  {
    id: "ins-analytics-01",
    environmentId: "env-analytics-batch",
    revisionId: "rev-120",
    status: "Stopped",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-22T10:02:00.000Z",
  },
  {
    id: "ins-analytics-02",
    environmentId: "env-analytics-batch",
    revisionId: "rev-120",
    status: "Stopped",
    clusterId: "cluster-tenant-central",
    startedAt: "2026-07-22T10:02:10.000Z",
  },
  {
    id: "ins-lab-01",
    environmentId: "env-agent-lab",
    revisionId: "rev-130",
    status: "Ready",
    clusterId: "cluster-tenant-east",
    startedAt: "2026-07-29T07:32:00.000Z",
  },
  {
    id: "ins-lab-02",
    environmentId: "env-agent-lab",
    revisionId: "rev-130",
    status: "Ready",
    clusterId: "cluster-tenant-west",
    startedAt: "2026-07-29T07:32:10.000Z",
  },
  {
    id: "ins-lab-03",
    environmentId: "env-agent-lab",
    revisionId: "rev-130",
    status: "Ready",
    clusterId: "cluster-tenant-central",
    startedAt: "2026-07-29T07:32:20.000Z",
  },
];

export const MOCK_CLUSTERS: readonly Cluster[] = [
  {
    id: "cluster-tenant-east",
    name: "Tenant Dedicated East",
    tenantId: "tenant-agent-paas-demo",
    dedicated: true,
    region: "us-east-1",
    status: "Healthy",
    readyCapacity: 56,
    totalCapacity: 64,
  },
  {
    id: "cluster-tenant-west",
    name: "Tenant Dedicated West",
    tenantId: "tenant-agent-paas-demo",
    dedicated: true,
    region: "us-west-2",
    status: "Healthy",
    readyCapacity: 42,
    totalCapacity: 48,
  },
  {
    id: "cluster-tenant-central",
    name: "Tenant Dedicated Central",
    tenantId: "tenant-agent-paas-demo",
    dedicated: true,
    region: "eu-central-1",
    status: "Degraded",
    readyCapacity: 25,
    totalCapacity: 32,
  },
];

export const MOCK_PROFILES: readonly Profile[] = [
  {
    id: "runtime-balanced",
    name: "Balanced RuntimePlan",
    kind: "RUNTIME",
    version: 4,
    summary: "General-purpose runtime with predictable concurrency.",
    controls: ["2 vCPU", "4 GiB memory", "20 concurrent sessions"],
  },
  {
    id: "runtime-high-memory",
    name: "High Memory RuntimePlan",
    kind: "RUNTIME",
    version: 3,
    summary: "Memory-optimized runtime for retrieval-heavy agents.",
    controls: ["4 vCPU", "16 GiB memory", "12 concurrent sessions"],
  },
  {
    id: "runtime-burst",
    name: "Burst RuntimePlan",
    kind: "RUNTIME",
    version: 6,
    summary: "Fast scale-out runtime for demos and variable traffic.",
    controls: ["2 vCPU", "2 GiB memory", "40 concurrent sessions"],
  },
  {
    id: "runtime-secure",
    name: "Secure RuntimePlan",
    kind: "RUNTIME",
    version: 2,
    summary: "Hardened runtime for sensitive control-plane workloads.",
    controls: ["2 vCPU", "8 GiB memory", "restricted syscalls"],
  },
  {
    id: "ingress-private",
    name: "Private Ingress",
    kind: "INGRESS",
    version: 5,
    summary: "Authenticated tenant ingress with managed TLS.",
    controls: ["tenant SSO", "rate limits", "managed TLS"],
  },
  {
    id: "egress-restricted",
    name: "Restricted Egress",
    kind: "EGRESS",
    version: 8,
    summary: "Default-deny egress with an explicit destination allowlist.",
    controls: ["default deny", "DNS policy", "destination audit"],
  },
  {
    id: "secure-task-hardened",
    name: "Hardened SecureTask",
    kind: "SECURE_TASK",
    version: 3,
    summary: "Isolated task execution with bounded filesystem access.",
    controls: ["ephemeral workspace", "resource limits", "signed artifacts"],
  },
  {
    id: "identity-workload",
    name: "Workload Identity",
    kind: "IDENTITY",
    version: 7,
    summary: "Short-lived workload identity without embedded credentials.",
    controls: ["short-lived tokens", "audience binding", "automatic rotation"],
  },
  {
    id: "logging-audit",
    name: "Control-plane Audit Logging",
    kind: "LOGGING",
    version: 9,
    summary: "Tenant-visible structured audit events.",
    controls: ["request correlation", "immutable event IDs", "30-day demo view"],
  },
  {
    id: "domain-customer-service",
    name: "Customer Service Domain",
    kind: "DOMAIN",
    version: 2,
    summary: "Domain policy pack for customer-service workloads.",
    controls: ["approved tools", "PII handling", "handoff policy"],
  },
];

export const MOCK_AUDIT_EVENTS: readonly AuditEvent[] = [
  {
    id: "audit-deploy-rev-42",
    kind: "CONTROL_PLANE",
    type: "REVISION_DEPLOYED",
    actor: "release-bot",
    targetId: STABLE_REVISION_ID,
    occurredAt: "2026-07-28T09:05:00.000Z",
    summary: "Deployed stable customer-service revision 42",
    details: {
      requestId: "req-20260728-001",
      operationId: "op-20260728-001",
      taskId: "task-20260728-001",
      environmentId: PRIMARY_ENVIRONMENT_ID,
    },
  },
  {
    id: "audit-failed-rev-43",
    kind: "CONTROL_PLANE",
    type: "REVISION_FAILED",
    actor: "release-bot",
    targetId: FAILED_REVISION_ID,
    occurredAt: "2026-07-29T06:14:00.000Z",
    summary: "Revision 43 failed readiness checks",
    details: {
      requestId: "req-20260729-002",
      operationId: "op-20260729-002",
      taskId: "task-20260729-002",
      environmentId: PRIMARY_ENVIRONMENT_ID,
    },
  },
  {
    id: "audit-access-cs-001",
    kind: "ACCESS",
    type: "SESSION_ROUTED",
    actor: "demo-user-1024",
    targetId: "ins-cs-02",
    occurredAt: "2026-07-29T06:30:00.000Z",
    summary: "Routed an authenticated session to a ready instance",
    details: {
      requestId: "req-20260729-003",
      operationId: "op-20260729-003",
      taskId: "task-20260729-003",
      environmentId: PRIMARY_ENVIRONMENT_ID,
    },
  },
  {
    id: "audit-security-egress-001",
    kind: "SECURITY",
    type: "UNAUTHORIZED_EGRESS_DENIED",
    actor: "policy-enforcer",
    targetId: "ins-cs-01",
    occurredAt: "2026-07-29T07:12:00.000Z",
    summary: "Denied an unauthorized egress attempt",
    details: {
      requestId: "req-20260729-004",
      operationId: "op-20260729-004",
      taskId: "task-20260729-004",
      environmentId: PRIMARY_ENVIRONMENT_ID,
      instanceId: "ins-cs-01",
      policyId: "egress-restricted",
      destination: "unapproved.example.invalid:443",
      decision: "DENY",
    },
  },
  {
    id: "audit-runtime-claims-001",
    kind: "RUNTIME",
    type: "INSTANCE_HEALTH_DEGRADED",
    actor: "runtime-controller",
    targetId: "ins-claims-03",
    occurredAt: "2026-07-29T07:20:00.000Z",
    summary: "Claims instance failed its health probe",
    details: {
      requestId: "req-20260729-005",
      operationId: "op-20260729-005",
      taskId: "task-20260729-005",
      environmentId: "env-claims-prod",
    },
  },
  {
    id: "audit-control-staging-001",
    kind: "CONTROL_PLANE",
    type: "DEPLOYMENT_STARTED",
    actor: "cx-platform",
    targetId: "env-customer-service-staging",
    occurredAt: "2026-07-29T08:00:00.000Z",
    summary: "Started the customer-service staging deployment",
    details: {
      requestId: "req-20260729-006",
      operationId: "op-20260729-006",
      taskId: "task-20260729-006",
      environmentId: "env-customer-service-staging",
    },
  },
];

export const MOCK_SECURITY_INCIDENTS: readonly SecurityIncident[] = [
  {
    id: OPEN_INCIDENT_ID,
    environmentId: PRIMARY_ENVIRONMENT_ID,
    title: "Denied unauthorized egress attempt",
    severity: "High",
    status: "Open",
    detectedAt: "2026-07-29T07:12:00.000Z",
    auditEventIds: ["audit-security-egress-001"],
    context: {
      instanceId: "ins-cs-01",
      policyId: "egress-restricted",
      destination: "unapproved.example.invalid:443",
      decision: "DENY",
    },
  },
  {
    id: "sec-20260725-002",
    environmentId: "env-payments-prod",
    title: "Unexpected task capability request",
    severity: "Medium",
    status: "Resolved",
    detectedAt: "2026-07-25T11:00:00.000Z",
    resolvedAt: "2026-07-25T11:12:00.000Z",
    auditEventIds: [],
    context: {
      policyId: "secure-task-hardened",
      decision: "DENY",
    },
  },
];
